### ISSUE TITLE
Cant send messages on macOS (14.2.0)

### ISSUE THREAD

**Issue by trevoroleary** [wtfaremyinitials/osa-imessage#31]
I was using apple script to send messages before this but those scripts are seemingly broken as well. Anybody know what might have changed? This is the error I got when running the echo.js (I censored the phone number)
```
(node:29344) UnhandledPromiseRejectionWarning: Error: Command failed: /usr/bin/osascript -l JavaScript
execution error: Error: Error: no thread with handle '+14xxxxxxxx1' (-2700)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:29344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 3DJakob** [comment]
I got the same problem! Any fix yet?

**Comment by wtfaremyinitials** [comment]
It looks like Apple may have (un?)intentionally broken that API. I’ll see what I can do

**Comment by RandallKent** [comment]
A couple of observations: 
1. Access to `~/Library/Messages/` has been restricted in Catalina ([blog](https://spin.atomicobject.com/2020/05/22/search-imessage-sql/))
1. `buddies` have become `participants` 

![Screen Shot 2021-02-21 at 11 18 52 y1KFOlLQ-62hvuicj-9Aq0T3VE](https://user-images.githubusercontent.com/51821/108631254-e8ef8780-7436-11eb-8502-d17d4e60973d.png)

I was able to get `echo.js` to work by granting access to `~/Library/Messages/` and changing [index.js:104](https://github.com/wtfaremyinitials/osa-imessage/blob/master/index.js#L104) from

```js
target = Messages.buddies.whose({ handle: handle })[0]
```

to 

```js
target = Messages.participants.whose({ handle: handle })[0]
```
