### ISSUE TITLE
Seems very broken on latest macOS (12.4)

### ISSUE THREAD

**Issue by mlfarrell** [wtfaremyinitials/osa-imessage#35]
```(node:27213) UnhandledPromiseRejectionWarning: Error: SQLITE_MISUSE: Database is closed
    at Database.all (/Users/mike/comp/js/nophone/node_modules/sqlite3/lib/sqlite3.js:18:25)
    at /Users/mike/comp/js/nophone/node_modules/sqlite/main.js:248:19
    at new Promise (<anonymous>)
    at Database.all (/Users/mike/comp/js/nophone/node_modules/sqlite/main.js:247:12)
    at Timeout.check [as _onTimeout] (/Users/mike/comp/js/nophone/node_modules/osa-imessage/index.js:153:39)```

This is AFTER granting terminal + node access to the filesystem.

**Comment by mlfarrell** [comment]
nvm.  my own exception killed the db connection.
